### ISSUE TITLE
NYUv2 classes

### ISSUE THREAD

**Issue by JingweiZhang12** [lorenmt/mtan#11]
Hi.  
For NYUv2 dataset,  the label I read from the original dataset is more than 13 categories, maybe dozens of categories.  The pre-processed label you provides is range from -1 to 12.  I want to know how you transform the original  labels to final labels with only 13 classes or  whether you have discarded some classes?  Also, do you know the numbers of final labels, e.g. -1 ,0, 1 , represent which class respectively?
I will appreciate it if you can offer more helpful information about the NYUv2 dataset.

**Comment by lorenmt** [comment]
We use the transformation from this repo: https://github.com/ankurhanda/SceneNetv1.0/ which is standard in most NYUv2 based segmentation tasks.

**Comment by lorenmt** [comment]
And you can directly download the raw 13-class NYUv2 files here: https://github.com/ankurhanda/nyuv2-meta-data

**Comment by JingweiZhang12** [comment]
Many thanks!
