### ISSUE TITLE
Did you mask out pixels where the ground truth is missing?

### ISSUE THREAD

**Issue by KejieLyu** [lorenmt/mtan#13]
Hello. Did you mask out pixels where the ground truth is missing for surface normal estimation and depth prediction as <Predicting Depth, Surface Normals and Semantic Labels with a Common Multi-scale Convolutional Architecture>?

**Comment by lorenmt** [comment]
Yes. Binary masks are applied to zero out the invalid gradients. Please check the loss functions implementation for more details.

On Mon, Oct 7, 2019 at 8:33, KejieLyu <notifications@github.com> wrote:
Hello. Did you mask out pixels where the ground truth is missing for surface normal estimation and depth prediction as <Predicting Depth, Surface Normals and Semantic Labels with a Common Multi-scale Convolutional Architecture>?

**Comment by KejieLyu** [comment]
Thank you.
