### ISSUE TITLE
cityscapes depth

### ISSUE THREAD

**Issue by JingweiZhang12** [lorenmt/mtan#15]
I noticed that the number of invalid depth pixels in a cityscapes depth image you provided is more than three-quarters of the total number of pixels in the image. So that's the original number of invalid depth or did you do the extra processing? In addition, during the training, the rel-depth-error is too large. Can you explain your preprocessing about the raw depth data in cityscapes?  Is it the same as the following:

disparity = (p-1)/256,   for each pixel p with p > 0
depth = baseline * fx / disparity,  where baseline=0.20, fx=2262

**Comment by lorenmt** [comment]
Hi,

As consistent with prior works, we directly use raw disparity images from official CityScapes dataset as ground-truth (inverse) depth labels. We did not compute the true depth using additional processing. 

Different from NYUv2 which is the gound-truth depth (measured in meters), the CityScapes dataset uses inverse depth (measured in meters^(-1)). 

Besides, If I remember correctly, the invalid points should only be a minimal amount from the images. Could you provide visualizations of an example of a depth image and its corresponding binary mask in the comment below and I will take a look to provide additional help?

Sk.

**Comment by JingweiZhang12** [comment]
![image](https://user-images.githubusercontent.com/34888372/68476677-58535f00-0266-11ea-8614-464387849afb.png)
The above is the depth map and binaty mask. Is this normal?

**Comment by lorenmt** [comment]
Yes. I believe you are doing right. You can see those artifacts are mainly from the edges of the objects or the inconsistent view differences. From the mask you provided, it's obviously less than 10% of the total pixels in the image, not the 3/4 as you claimed in the first post.

**Comment by JingweiZhang12** [comment]
Yes.  Thanks for your reply!
