### ISSUE TITLE
file structure

### ISSUE THREAD

**Issue by xingdw** [lorenmt/mtan#17]
Wish you show me your file(data) structure.I can't run this program since I don't konw how to prepare the data

**Comment by xingdw** [comment]
And I wanner the is there npy file in origin data ? I see the program load the npy file in create_dataset.py

**Comment by lorenmt** [comment]
Please carefully read the readme document which has already explained how to prepare the data. It's quite simple: just to download the files I attached in the dropbox links.

**Comment by xingdw** [comment]
Thanks for your reply, but I can't open that url in China.

**Comment by xingdw** [comment]
Thank you, all is ok
