### ISSUE TITLE
NYU2_ dataset, npy file

### ISSUE THREAD

**Issue by xingdw** [lorenmt/mtan#19]
I'm sorry but I can't understand the npy file, like this.
![image](https://user-images.githubusercontent.com/50009373/70965768-d3146300-20cb-11ea-8168-a5b0f051cbe9.png)
where can I get this npy file?Thank you

**Comment by xingdw** [comment]
these npy files will be read in create_dataset.py file

**Comment by lorenmt** [comment]
Please carefully read the readme document.
