### ISSUE TITLE
Conv init

### ISSUE THREAD

**Issue by brdav** [lorenmt/mtan#20]
Hi,
thanks for the code! It seems that the initialization for Conv is never used in model_wrn_mtan.py:
https://github.com/lorenmt/mtan/blob/6c8e6a4c1f27633d93a8010ac734cd5d4c4d4dfe/visual_decathlon/model_wrn_mtan.py#L17
Are MTAN modules sensitive to initializations in your experience? Was there a reason you chose Xavier uniform specifically?
Best

**Comment by lorenmt** [comment]
Hi, from the best of my knowledge, MTAN is not sensitive to initialisations.

There is no specific reason I picked Xavier uniform, I just used that as a default initialisation for all of my projects.

Hope that helps.

**Comment by brdav** [comment]
Thanks
