### ISSUE TITLE
My own dataset

### ISSUE THREAD

**Issue by ntelo007** [lorenmt/mtan#22]
Good evening,

I would like to use your repo with my own dataset. Images are of size 256x256 pixels and I have 5 different ground truth sets of the same size. Some are binary images and some other tasks contain multiple classes. 

Could you please guide me on what I need to change to train your proposed model?

Thank you very much for your time.

**Comment by lorenmt** [comment]
Hi,

I suggest you first check out the create_data file, to understand what it is doing, and then you can modify or add your own class of data loader using this similar format.

Then, you should also take a look at any multi-task network file in the folder, to modify the current three tasks into 5 or any number of tasks for your own interests.

I believe the code itself is quite self-explanatory. It shouldn't be that hard to understand.

Sk.
