### ISSUE TITLE
Some questions about visual_decathlon

### ISSUE THREAD

**Issue by chris20181220** [lorenmt/mtan#24]
hi @lorenmt Thanks for sharing your high-quality code .
 
1.  I  download the dataset and devkit at the official Visual Decathlon Challenge website, and run python model_wrn_mtan.py for training , the result seems much lower than yours . Is there someting wrong with my code? and  I find visual_decathlon did not use DWA module 

EPOCH: 0398 | DATASET: aircraft || TRAIN: 4.4714 0.0295 || TEST: 4.5622 0.0113
EPOCH: 0398 | DATASET: cifar100 || TRAIN: 3.9217 0.1044 || TEST: 4.4817 0.0232
EPOCH: 0398 | DATASET: daimlerpedcls || TRAIN: 0.5747 0.7077 || TEST: 0.8359 0.5173
EPOCH: 0398 | DATASET: dtd || TRAIN: 3.4813 0.1200 || TEST: 3.5718 0.0908
EPOCH: 0398 | DATASET: gtsrb || TRAIN: 2.4235 0.2809 || TEST: 3.5151 0.0662
EPOCH: 0398 | DATASET: omniglot || TRAIN: 6.6661 0.0077 || TEST: 8.3716 0.0012
EPOCH: 0398 | DATASET: svhn || TRAIN: 2.0999 0.2669 || TEST: 2.3221 0.0960
EPOCH: 0398 | DATASET: ucf101 || TRAIN: 4.2835 0.0416 || TEST: 4.2502 0.0405
EPOCH: 0398 | DATASET: vgg-flowers || TRAIN: 3.8070 0.1078 || TEST: 3.5612 0.1459

EPOCH: 0399 | DATASET: aircraft || TRAIN: 4.4398 0.0367 || TEST: 4.5639 0.0136
EPOCH: 0399 | DATASET: cifar100 || TRAIN: 3.7655 0.1223 || TEST: 4.4952 0.0246
EPOCH: 0399 | DATASET: daimlerpedcls || TRAIN: 0.5523 0.7139 || TEST: 0.8194 0.6353
EPOCH: 0399 | DATASET: dtd || TRAIN: 3.5056 0.1171 || TEST: 3.5246 0.1028
EPOCH: 0399 | DATASET: gtsrb || TRAIN: 2.3447 0.2975 || TEST: 3.5864 0.0551
EPOCH: 0399 | DATASET: omniglot || TRAIN: 6.9420 0.0035 || TEST: 7.3892 0.0014
EPOCH: 0399 | DATASET: svhn || TRAIN: 2.1091 0.2652 || TEST: 2.3105 0.1013
EPOCH: 0399 | DATASET: ucf101 || TRAIN: 4.3354 0.0334 || TEST: 4.2975 0.0337
EPOCH: 0399 | DATASET: vgg-flowers || TRAIN: 4.2414 0.0676 || TEST: 3.7590 0.0885

2. when I run python coco_results.py, there is a error:
    Traceback (most recent call last):
  File "coco_results.py", line 7, in <module>
    pickle_in = open("imagenet.pickle","rb")
FileNotFoundError: [Errno 2] No such file or directory: 'imagenet.pickle'

I can't find  this file 'imagenet.pickle'

**Comment by lorenmt** [comment]
Hi,

Thanks for being interested in our work. I have updated the `eval` file, which I found that does not save imagenet pickle file properly. Could you rerun the code, and check the new results?

Since ImageNet is significantly larger than the other datasets, as you can see from the training file, we first save ImageNet result first at epoch 300, and then fine-tuning another 100 epochs for the rest of the datasets.

So you need to do evaluation separately for `imagenet` and `nonimagenet`. And then run the coco_results.py.

But from your attached performance, there was definitely something wrong with the training side. Could you provide the results for the entire training epochs?

So I can have a detailed look...

Thanks.

**Comment by lorenmt** [comment]
Also, could you confirm whether the `scheduler.step()` has been moved properly due to the new pytorch version update? I have also fixed this problem just now... 

From your posted results, it seems that the network was not updated properly.

**Comment by chris20181220** [comment]
> Hi,
> 
> Thanks for being interested in our work. I have updated the `eval` file, which I found that it does not save imagenet pickle file properly. Could you rerun the code, and check the new results?
> 
> Since ImageNet is significantly larger than the other datasets, as you can see from the training file, we first save ImageNet result at epoch 300, and then fine-tuning another 100 epochs for the rest of the datasets.
> 
> So you need to do evaluation separately for `imagenet` and `nonimagenet`. And then run the coco_results.py.
> 
> But from your attached performance, there was definitely something wrong with the training side. Could you provide the results for the entire training epochs?
> 
> So I can have a detailed look...
> 
> Thanks.

Thanks for the quick response.
there is another question when i rerun the eval code. The test annotations contain only the image names and not class labels, so the code 
`im_test_set[i] = torch.utils.data.DataLoader(torchvision.datasets.ImageFolder(data_path + data_name[i] + '/test',
                                                 transform=data_transform(data_path, data_name[i], train=False)),
                                                 batch_size=100,
                                                 shuffle=False)` 
will make an error like this:

_Traceback (most recent call last):
  File "model_wrn_eval.py", line 229, in <module>
    transform=data_transform(data_path, data_name[i], train=False)),
  File "/usr/local/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 178, in __init__
    target_transform=target_transform)
  File "/usr/local/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 79, in __init__
    "Supported extensions are: " + ",".join(extensions)))
RuntimeError: Found 0 files in subfolders of: decathlon-1.0-data/imagenet12/test
Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif_

**Comment by chris20181220** [comment]
> Also, could you confirm whether the `scheduler.step()` has been moved properly due to the new pytorch version update? I have also fixed this problem just now...
> 
> From your posted results, it seems that the network was not updated properly.

thanks very much and I will retrain the model immediately

**Comment by lorenmt** [comment]
Hi Chris,

Sorry for the confusion in the code. I will take a detailed look and re-run in my own and get back to you.

Sk.

**Comment by chris20181220** [comment]
> confusion

thanks

**Comment by lorenmt** [comment]
Hello,

I made some modifications to the code, and they should all work correctly now. I have also fully tested each component, and they are good to go.

Could you check out the updated readme, and follow each step to run the code.

For 'eval' mode (not train on validation dataset), you should be expected to see the reported TEST (actually should be validation performance) results roughly close to the one reported in the paper. For evaluating the test dataset, please run the code in `all` mode, so it trains on both the training and validation dataset.

Let me know whether this works.

Sk.
