### ISSUE TITLE
about the backbone model

### ISSUE THREAD

**Issue by liyangliu** [lorenmt/mtan#26]
Hi, @lorenmt,

I read your code and found that on NYUv2, you use VGG as the backbone, but
1. it is not implemented by vgg in torchvision, which exact vgg structure do you use?
2. it is not initialized by the model pretrained on ImageNet. Why is it the case?

Thanks.

**Comment by lorenmt** [comment]
Hello,

1. We used VGG-16, specifically SegNet which is composed of encoder-decoder VGG-16 type of layers.
2. We want to understand its true generalization ability, and thus we did not apply any pre-trained weights. 

Hope that helps.
