### ISSUE TITLE
Question about the architecture

### ISSUE THREAD

**Issue by minygd** [lorenmt/mtan#27]
Hello, I have a question about the architecture of the model. In Fig.2, is the `pool` in Attention Module for Encoder the same as the same stage in VGG? And so as the `samp` in Decoder part.
Thanks for your time!

**Comment by lorenmt** [comment]
Hi,

I am not sure I understand your question correctly. Do you want to ask whether the design of the pooling and sampling function in the attention module and the shared network is the same? If so, yes they are the same. `pool` uses MaxPool(2, 2) and `samp` uses Bilinear sampling.

For detailed design, I suggest checking out the original code.

**Comment by minygd** [comment]
OK, thanks. I got it!
