### ISSUE TITLE
number of parameters

### ISSUE THREAD

**Issue by cheer00** [lorenmt/mtan#30]
`def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

print('Parameter Space: ABS: {:.1f}, REL: {:.4f}\n'.format(count_parameters(SegNet),
                                                           count_parameters(SegNet)/24981069))`

what is the meaning of 24981069", why is the total parameters devided by 24981069 ?  What is the unit of  parameters?

**Comment by lorenmt** [comment]
Thanks @Manchery for the explanation. 

Yes, this number represents the parameter space of single task network. So in REL, we print out the percentage of the number of parameter space in multi-task network relative to the single task network.
