### ISSUE TITLE
how to save and evaluate the model in the im2im_pred folder?

### ISSUE THREAD

**Issue by Sunyingchun** [lorenmt/mtan#33]
First, Thanks for your amazing work!
When I run the program in the im2im_pred folder, I don't know how to save and evaluate the model. And I don't know whether I've missed some of the highlights abou this aspect. I would appreciate it if you could answer me.
If there are some grammatical errors, please forgive me.

**Comment by Manchery** [comment]
Hi @Sunyingchun 

For saving the model, it is a basic operation in Pytorch. If you are familiar with torch, you can easily add your code to save and load model with `model.state_dict()`, `torch.save` and `torch.load`.

For evaluating the model, NYUv2 dataset has only two splits, namely train set and validate set. What the code prints in the screen are exactly evaluating the training model on the validate set.

Please forgive my race to be the first to answer the question @lorenmt. Please correct me if any mistake made.

**Comment by Manchery** [comment]
I think there is a similar issue: [model_segnet_mtan prediction code · Issue #31 · lorenmt/mtan](https://github.com/lorenmt/mtan/issues/31)

**Comment by Sunyingchun** [comment]
Thanks for your quick answer.
