### ISSUE TITLE
Avg cost function

### ISSUE THREAD

**Issue by vesaalexandru95** [lorenmt/mtan#37]
Hello ! 
Can you explain please why did you initialize the avg cost function with  24?
eg :      avg_cost = np.zeros([total_epoch, 24], dtype=np.float32)

**Comment by lorenmt** [comment]
Hello,

It's a 24 dimensonal vector not initialised into 24. Please check out the line here: https://github.com/lorenmt/mtan/blob/4e02f9fee0bc5935977fa043c9adb9d2d21689bd/im2im_pred/utils.py#L214.

**Comment by vesaalexandru95** [comment]
Thanks a lot !
