### ISSUE TITLE
 relative descending rate

### ISSUE THREAD

**Issue by Zxlan** [lorenmt/mtan#4]
Why is the  relative descending rate a quotient of two epoch losses, not a gradient?

**Comment by lorenmt** [comment]
Due to the randomness from mini-batch. Calculate the gradient will result in a large fluctuation. For example, for t=0, L = 0.5 and t=1, L= 0.6, in such case, the gradient would be negative and the adaptive weighting will strongly bias to the other task. While using the quotient still maintain the relative descending rate and yet more robust to this based on my experience. Hope that helps.

**Comment by Zxlan** [comment]
So what if the gradient is not negative, that is to say, absolute value?


------------------ 原始邮件 ------------------
发件人: "Shikun Liu"<notifications@github.com>;
发送时间: 2019年6月24日(星期一) 凌晨5:34
收件人: "lorenmt/mtan"<mtan@noreply.github.com>;
抄送: "瑶望&兰馨"<1069081791@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [lorenmt/mtan]  relative descending rate (#4)




Due to the randomness from mini-batch. Calculate the gradient will result in a large fluctuation. For example, for t=0, L = 0.5 and t=1, L= 0.6, in such case, the gradient would be negative and the adaptive weighting will strongly bias to the other task. While using the quotient still maintain the relative descending rate and yet more robust to this based on my experience. Hope that helps.

**Comment by lorenmt** [comment]
That becomes worse. Say task 1: t=0, L=0.5, t=1, L=0.4 and task2: t=0, L=0.5, t=1, L=0.9. Apparently, we need to put more weighting on task 2. However, if we use absolute value, then the task weighting will toward task 1.

**Comment by Zxlan** [comment]
In this example, the weight of hutask2 is larger than that of task1.What do you think of the ideal weighted state?




------------------ 原始邮件 ------------------
发件人: "Shikun Liu"<notifications@github.com>;
发送时间: 2019年6月24日(星期一) 上午9:40
收件人: "lorenmt/mtan"<mtan@noreply.github.com>;
抄送: "瑶望&兰馨"<1069081791@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [lorenmt/mtan]  relative descending rate (#4)




That becomes worse. Say task 1: t=0, L=0.5, t=1, L=0.4 and task2: t=0, L=0.5, t=1, L=0.9. Apparently, we need to put more weighting on task 2. However, if we use absolute value, then the task weighting will toward task 1.

**Comment by lorenmt** [comment]
We need the task weighting towards task 2 since the loss 2 increases for the following epoch. It means either task 1 is an easy task which dominates the multi-task learning or the task weighting towards more on task 1 for the last epoch.

**Comment by Zxlan** [comment]
What do you mean towards？Can you speak Chinese




------------------ 原始邮件 ------------------
发件人: "Shikun Liu"<notifications@github.com>;
发送时间: 2019年6月24日(星期一) 上午10:18
收件人: "lorenmt/mtan"<mtan@noreply.github.com>;
抄送: "瑶望&兰馨"<1069081791@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [lorenmt/mtan]  relative descending rate (#4)




We need the task weighting towards task 2 since the loss 2 increases for the following epoch. It means either task 1 is an easy task which dominates the multi-task learning or the task weighting towards more on task 1 for the last epoch.
