### ISSUE TITLE
depth and segmentation label in cityscape

### ISSUE THREAD

**Issue by TianhaoFu** [lorenmt/mtan#41]
Hi,

In your preprocessed cityscape dataet, there exit a segment label -1 . 
What mean of that?
byw, do you know the max depth of cityscape?

thanks so much!

**Comment by lorenmt** [comment]
-1 represents invalid pixels which would not compute gradients during backprop. These pixels would not be included for mIoU or accuracy metrics.

Sorry no, I don't have max depth for cityscapes.
