### ISSUE TITLE
NYUv2 surface normals grey boundary

### ISSUE THREAD

**Issue by NareshGuru77** [lorenmt/mtan#42]
Hi,

I downloaded the precomputed NYUv2 surface normals ground truth as mentioned in the readme (nyu link). I see that there is a grey border surrounding the surface normal ground truth image as in one example below:

![0000](https://user-images.githubusercontent.com/26181088/114562423-c75c9080-9c6e-11eb-8910-5dfc26b752a4.png)

could you let me know whether you also observed this ?

**Comment by lorenmt** [comment]
Hi Naresh,
  
​
  
​Yes. In the pre-processing version I linked, we crop the images in order to remove these invalid pixels. The gray border exist​s is because the ground-truth depth is not perfect. And the normal is the derivative of the depth, so it would be affected.
  
​
  
​Hope that helps.
