### ISSUE TITLE
Missing items in cityscapes/val/label_19

### ISSUE THREAD

**Issue by zhanglijun95** [lorenmt/mtan#43]
Hi there,
I downloaded the [256x512, 2.42GB] version of the Cityscapes dataset and found that there are only 490 files in _val/label_19_ but 500  in other corresponding folders. I checked the Dropbox folder roughly and found out that some files like _390.npy_ is missing. Could you please help me with the missing files? 
Thank you very much!

**Comment by lorenmt** [comment]
Hi,

I am really sorry for the missing files, might due to the file-syncing issue from the recent data reorganization. If you re-open the same link now, the problem should have been solved.

**Comment by zhanglijun95** [comment]
Problem fixed. Thank you!
