### ISSUE TITLE
DWA

### ISSUE THREAD

**Issue by long123524** [lorenmt/mtan#48]
您好，我想问一下您的多任务损失函数中DWA是在哪定义的和调用呢？另外，在多任务网络中可以存在多个优化器嘛？

**Comment by lorenmt** [comment]
请参看： https://github.com/lorenmt/mtan/blob/268c5c1796bf972d1e0850dcf1e2f2e6598cc589/im2im_pred/utils.py#L128
且仔细阅读 readme 里各项 flag 的用途。
