### ISSUE TITLE
The para Temperature of DWA 

### ISSUE THREAD

**Issue by ykeivn** [lorenmt/mtan#49]
您好，我想问一下联合多任务损失函数中DWA的Temperature的取值范围在多少合适呢，依据什么来选择得到文章中的2呢？（loss值的大小？），先提前感谢您的回答

**Comment by lorenmt** [comment]
Hello, 通常是 0.5 - 5 之间。 T = 2通常就 work 的还行。

**Comment by ykeivn** [comment]
比如我的模型第一个epoch计算得到的损失函数大小为2以下，选择过大的T值能work吗？我先跑一些值试试吧，有什么问题可能还得麻烦您，谢谢

**Comment by lorenmt** [comment]
T 越大 weighting 的波动是越小。loss 的结果大不大无所谓 只要都在一个 scale 就行，比如都是 pixel-based 的。

我目前在做一个工作效果比 DWA 强非常多，准备投 ICLR，即将开源你到时候也可以参考一下。

**Comment by ykeivn** [comment]
好嘞，这就关注大佬

**Comment by LMerCy** [comment]
@lorenmt Have you ever open source your ICLR work?

**Comment by lorenmt** [comment]
> 

All my works were open-souced. Which work you were talking about?
