### ISSUE TITLE
Vanila SegNet

### ISSUE THREAD

**Issue by donhk1011** [lorenmt/mtan#5]
Hi,

I found that there is no 'relu' activation in the One Task architecture except the last prediction layers. 
https://github.com/lorenmt/mtan/blob/master/im2im_pred/model_segnet_single.py#L22

Is it the same as the original SegNet?

**Comment by lorenmt** [comment]
Hi, It has the 'relu', please refer to the conv_layer function defined in: 
https://github.com/lorenmt/mtan/blob/aa77e6bb0f1832a633b67bd0374f106a1668cd27/im2im_pred/model_segnet_single.py#L68

**Comment by donhk1011** [comment]
Oh thanks! I understood it the other way around.
