### ISSUE TITLE
Avg Cost accumulation

### ISSUE THREAD

**Issue by sofiapvcp** [lorenmt/mtan#53]
Hi,

If I understand your code correctly, the dynamic weights are calculated using the unweighted loss of each epoch `(train_loss)` , which is accumulated in the `avg_cost `variable. Shouldn't the weighted loss `(loss)` be accumulated instead? Or would we lose the sense of the training pace because the weights had already been applied?

Thank you for your time.

**Comment by lorenmt** [comment]
Hello,

Yes your understanding is correct. For example, let's say we have loss convergence speed 0.1 and 0.2 for two tasks, then based on the design of DWA, we should apply 0.666 and 0.333 for each task weighting so it's balanced. If we apply on the weighted loss instead, then the next epoch will give 0.5 and 0.5 which is not balanced. The compute of training pace must be on the original unweighted training loss. Hope that's clear.

**Comment by sofiapvcp** [comment]
Thank you!
