### ISSUE TITLE
Question about the pre-processed cityscapes

### ISSUE THREAD

**Issue by heendung** [lorenmt/mtan#57]
Thanks for releasing the code and dataset!

I have a question about the image in your pre-processed cityscapes. 
May I ask which pre-processed image corresponds to which image in the original cityscapes?
For example, Does "0.npy" in your training set match with "aachen_000000_000019_leftImg8bit.png" in the original training set?

Do you have a mapping list between your image names and the original image names? (e.g., "0.npy" - "aachen_000000_000019_leftImg8bit.png")

Thank you!

**Comment by lorenmt** [comment]
Sorry I don't have a mapping list. It's quite random.

**Comment by heendung** [comment]
Thanks! I would really appreciate it if the code is released soon!

**Comment by lorenmt** [comment]
https://github.com/lorenmt/auto-lambda/blob/main/dataset/cityscapes_preprocess.py
