### ISSUE TITLE
DWA的loss梯度爆炸问题

### ISSUE THREAD

**Issue by E18301194** [lorenmt/mtan#58]
您好  
我将您的DWA-loss策略  使用在停车位多任务中  ，这个任务是既有分割 又有检测的任务，
我希望解决任务中多任务负转移的问题   在我的实验中  第一个第二个epoch会正常收敛  但是在第三个epoch 梯度loss全部变为nan，我不明白其中的原因   希望可以得到您的帮助

**Comment by lorenmt** [comment]
hello. 你可以plot dwa 得到的weighting么?如果没有过分大或过分小..这应该是你自己loss 设计的问题.

**Comment by lorenmt** [comment]
Closed as no further updates.
