### ISSUE TITLE
Used Mtan on depth estimation and object detection

### ISSUE THREAD

**Issue by JiSuanJiDaWang** [lorenmt/mtan#60]
Hi, I am building the depth estimation and object detection networks using your mtan framework. I used equal weighting for each task and adam as optimiser. I found that the detection tasks perform quite bad during the training. But it performed reasonably when I trained it as single task attention network. Do you have any idea of why this happens. 

Many Thanks

**Comment by lorenmt** [comment]
Was the problem occured only on the detection task? Did the depth estimation perform well?

**Comment by JiSuanJiDaWang** [comment]
Hi, actually I did not visualise the performance of the depth estimation. I used the loss given by your code. But I found that the relative error on validation data set is negative value which is quite wired.

<img width="836" alt="image" src="https://user-images.githubusercontent.com/82489384/180471664-6620f88c-d0ce-4832-bd74-b0f77d798732.png">

**Comment by lorenmt** [comment]
If you look at the implementation of relative depth, the only possible reason is that your ground-truth depth is negative. I would suggest to recheck your data processing of depth, which might be the reason why your object detection was performing worse.

**Comment by JiSuanJiDaWang** [comment]
> f you look at the implementation of relative depth, the only possible reason is that your ground-truth depth is negative. I would suggest to recheck your data processing of depth, which might be the reason why your object detection was performing worse.

Thanks a lot. Looking into it right now!

**Comment by AndreasPapandreou** [comment]
> Hi, I am building the depth estimation and object detection networks using your mtan framework. I used equal weighting for each task and adam as optimiser. I found that the detection tasks perform quite bad during the training. But it performed reasonably when I trained it as single task attention network. Do you have any idea of why this happens.
Many Thanks


Hi, what changes did you apply to mtan framework to make the object detection work? Thank you in advance!

**Comment by JiSuanJiDaWang** [comment]
Hi, The wrong error(negative) on the depth estimation affects the performance of object detection in my network. After I modified the processing code, it worked.
