### ISSUE TITLE
This code repository is missing the code for the multitasking learning module

### ISSUE THREAD

**Issue by huangzhaor** [lorenmt/mtan#64]
Unable to find DWA implementation code for coordinating multiple tasks

**Comment by huangzhaor** [comment]
哥是这样的，README 中写道model_segnet_mtan.py是多目标的实现，点进去找不到DWA的实现，只在最后看到multi_task_trainer，但是这个函数的实现在库里是没有的。

**Comment by lorenmt** [comment]
> 哥是这样的，README 中写道model_segnet_mtan.py是多目标的实现，点进去找不到DWA的实现，只在最后看到multi_task_trainer，但是这个函数的实现在库里是没有的。

https://github.com/lorenmt/mtan/issues/64#issuecomment-2278539577

**Comment by lorenmt** [comment]
https://github.com/lorenmt/mtan/blob/c36c30baa18968dec74fe9039abcfd4f132edfa1/im2im_pred/utils.py#L128

**Comment by huangzhaor** [comment]
感谢您的解答
