### ISSUE TITLE
feature pyramid networks

### ISSUE THREAD

**Issue by chouscode** [lorenmt/mtan#65]
Hi, nice job. I found that the encoder only ues the last feature map for attention module. Is it possible to use FPN structure in MTAN ?

**Comment by lorenmt** [comment]
Of course. I could try to incorporate the attention modules on top of a FPN structure and see the results.

**Comment by chouscode** [comment]
Really? Looking forward to your results :)

**Comment by lorenmt** [comment]
> Really? Looking forward to your results :)

Sorry, I meant to say you can try to train such a model .. it should be relatively straightforward to modify.

**Comment by chouscode** [comment]
i will try this. thanks for your patience.
