### ISSUE TITLE
Any pretrained weights?

### ISSUE THREAD

**Issue by sunxm2357** [lorenmt/mtan#7]
Do you use any pretrained weights (e.g. VGG-16 on ImageNet) or you just start from scratch? The performance gap even for the baseline Cross Stitch on NYU v2 using VGG 16 is very interesting, and I am trying to find out the reason. Thanks!

**Comment by lorenmt** [comment]
No, we did not apply any pre-training. All of the models were trained from scratch. NYUv2 is a very hard dataset, pre-training can lead to a significant performance boost. However, we want to test the true generalisation ability from the network itself, thus no pre-training were used.

**Comment by sunxm2357** [comment]
Thanks.
