### ISSUE TITLE
Questions about decathlon challenge

### ISSUE THREAD

**Issue by colorjam** [lorenmt/mtan#8]
Thank you for sharing code. I'm puzzled about training  `python model_wrn_eval.py --dataset 'notimagenet'`. I can't find the flags about this setting.

**Comment by lorenmt** [comment]
https://github.com/lorenmt/mtan/blob/4a3406ca53912121974162531825e74b15f5fbc8/visual_decathlon/model_wrn_eval.py#L240 This line gives the details of 'notimagenet' flag.

**Comment by colorjam** [comment]
Sorry, I thought it was not training with Imagenet so I can't find the flags in `model_srn_mtan.py`. In `model_wrn_mtan.py`, the `data_path` only include `decathlon-data`, so during training you not use the Imagenet dataset? And you train the WideResNet from scratch instead of a pre-trained model?

**Comment by lorenmt** [comment]
So for decathlon challenge, we don't allow to use external data. So here the imagenet is the reduced resolution version included in the decathlon challenge. https://github.com/lorenmt/mtan/blob/4a3406ca53912121974162531825e74b15f5fbc8/visual_decathlon/model_wrn_mtan.py#L298 So in `model_wrn_mtan.py' we trained all datasets together but save imagenet features first then fine-tune to the other 9 datasets.
